In [1]:
import numpy as np
import pandas as pd

In [2]:
creditCard = pd.read_csv("creditcard.csv")

In [3]:
creditCard.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
creditCard.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
creditCard.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,3.918649e-15,5.682686e-16,-8.761736e-15,2.811118e-15,-1.552103e-15,2.040130e-15,-1.698953e-15,-1.893285e-16,-3.147640e-15,...,1.473120e-16,8.042109e-16,5.282512e-16,4.456271e-15,1.426896e-15,1.701640e-15,-3.662252e-16,-1.217809e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [6]:
creditCard.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [7]:
creditCard.duplicated().sum()

1081

In [8]:
creditCard = creditCard.drop_duplicates()

In [9]:
creditCard['Class'].value_counts()

0    283253
1       473
Name: Class, dtype: int64

In [10]:
valid = creditCard[creditCard.Class == 0]
fraud = creditCard[creditCard.Class == 1]

In [11]:
valid.Amount.describe()

count    283253.000000
mean         88.413575
std         250.379023
min           0.000000
25%           5.670000
50%          22.000000
75%          77.460000
max       25691.160000
Name: Amount, dtype: float64

In [12]:
valid_sample = valid.sample(n=473)
valid_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
24227,33128.0,-0.038917,-0.593676,1.887711,-2.320651,-0.835403,-0.321554,-1.552813,-0.664128,-2.364226,...,0.552728,-0.687606,-0.937541,0.223189,1.014453,-0.264645,0.137830,0.154345,3.00,0
268966,163463.0,1.780541,0.008474,-2.549174,1.574685,0.811630,-0.880434,0.755707,-0.285778,0.317556,...,0.018670,-0.104072,-0.106597,0.450011,0.402964,-0.524750,-0.035073,-0.003053,140.58,0
29818,35643.0,1.277113,0.178733,0.133747,0.374176,0.112387,-0.043977,-0.036665,-0.011309,0.103820,...,-0.285617,-0.786837,0.063205,-0.772704,0.255576,0.176447,-0.013793,0.006948,1.29,0
88888,62338.0,0.834334,-1.124481,1.059268,0.633288,-1.155744,1.116592,-1.010111,0.430277,-0.638138,...,-0.031302,0.224862,-0.102145,-0.290445,0.161966,-0.216896,0.093188,0.052255,168.00,0
203666,134914.0,-1.017648,-0.135220,1.450092,-3.017915,-1.260861,-0.582223,-0.716615,0.604859,-2.209782,...,-0.112685,-0.066267,-0.319898,0.012391,0.586331,-0.137229,0.144613,0.025830,4.40,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209508,137594.0,-0.303567,1.272570,-0.629907,-0.639135,0.681332,-0.843686,0.834094,0.025926,0.572695,...,-0.411709,-0.980362,0.145995,0.517714,-0.393531,0.129492,0.425575,0.202031,2.69,0
167512,118732.0,0.039053,0.834664,0.123602,-0.817722,0.727311,-0.519563,0.921950,-0.049882,-0.324420,...,-0.236955,-0.517556,-0.008790,-0.489842,-0.444520,0.149203,0.245491,0.083026,2.18,0
27331,34505.0,0.241774,0.905005,-1.339624,-0.239484,2.877735,3.118738,0.430258,0.732581,-0.653575,...,0.079035,0.302575,-0.027727,1.006272,-0.554599,-0.399759,0.442911,0.223262,1.14,0
211847,138595.0,2.059015,0.321851,-1.844094,1.238379,0.570146,-1.391101,0.778908,-0.478176,-0.065163,...,0.118482,0.431281,-0.012224,-0.098790,0.447852,-0.475437,-0.033257,-0.065166,8.36,0
121463,76201.0,1.131424,0.056694,0.773241,1.264985,-0.658225,-0.381354,-0.194245,0.104797,0.363831,...,-0.200126,-0.489025,0.049847,0.488587,0.427765,-0.552838,0.027777,0.017368,10.44,0

In [13]:
new_dataset = pd.concat([valid_sample, fraud], axis=0)

In [14]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
24227,33128.0,-0.038917,-0.593676,1.887711,-2.320651,-0.835403,-0.321554,-1.552813,-0.664128,-2.364226,...,0.552728,-0.687606,-0.937541,0.223189,1.014453,-0.264645,0.137830,0.154345,3.00,0
268966,163463.0,1.780541,0.008474,-2.549174,1.574685,0.811630,-0.880434,0.755707,-0.285778,0.317556,...,0.018670,-0.104072,-0.106597,0.450011,0.402964,-0.524750,-0.035073,-0.003053,140.58,0
29818,35643.0,1.277113,0.178733,0.133747,0.374176,0.112387,-0.043977,-0.036665,-0.011309,0.103820,...,-0.285617,-0.786837,0.063205,-0.772704,0.255576,0.176447,-0.013793,0.006948,1.29,0
88888,62338.0,0.834334,-1.124481,1.059268,0.633288,-1.155744,1.116592,-1.010111,0.430277,-0.638138,...,-0.031302,0.224862,-0.102145,-0.290445,0.161966,-0.216896,0.093188,0.052255,168.00,0
203666,134914.0,-1.017648,-0.135220,1.450092,-3.017915,-1.260861,-0.582223,-0.716615,0.604859,-2.209782,...,-0.112685,-0.066267,-0.319898,0.012391,0.586331,-0.137229,0.144613,0.025830,4.40,0

In [15]:
#to find the relevant features the correlation of all the attributes has been derived
correlation = new_dataset.corr()
#correlation of all attributes with "Class" is derived in descending order to find the most relevant features 
corr_target = correlation['Class'].sort_values(ascending=False)
corr_target

Class     1.000000
V4        0.703125
V11       0.675341
V2        0.478559
V19       0.257930
V20       0.205794
V8        0.122181
V27       0.107834
V21       0.101526
V28       0.092699
Amount    0.092606
V26       0.082612
V22       0.046960
V25       0.005765
V15      -0.009633
V13      -0.023285
V23      -0.041628
V24      -0.139106
Time     -0.153430
V5       -0.363223
V6       -0.398986
V1       -0.423631
V18      -0.455140
V7       -0.466570
V9       -0.538425
V17      -0.549055
V3       -0.562792
V16      -0.588754
V10      -0.627859
V12      -0.677324
V14      -0.746481
Name: Class, dtype: float64

In [16]:
#hence 'V11','V4','V2','V21','V19','V20','V8','V27' are most relevant 
x = creditCard[['V11','V4','V2','V21','V19','V20','V8','V27']]
y = creditCard['Class']

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# LOGISTIC REGRESSION

In [19]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [20]:
model_pred = model.predict(x_test)

In [28]:
accuracy = accuracy_score(y_test,model_pred)
print("Logistic Regression Accuracy",accuracy*100)

Logistic Regression Accuracy 99.89602791386177

In [36]:
class_report = classification_report(y_test,model_pred)
print("Logistic Regression Classification_report:\n",class_report)

Logistic Regression Classification_report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56656
           1       0.86      0.41      0.56        90

    accuracy                           1.00     56746
   macro avg       0.93      0.71      0.78     56746
weighted avg       1.00      1.00      1.00     56746

# DECISION TREE

In [29]:
model2 = DecisionTreeClassifier(random_state=42)
model2.fit(x_train,y_train)

DecisionTreeClassifier(random_state=42)

In [30]:
model2_pred = model2.predict(x_test)

In [31]:
accuracy2 = accuracy_score(y_test,model2_pred)
print("Decision Tree Accuracy:",accuracy2*100)

Decision Tree Accuracy: 99.88016776512882

In [37]:
class_report2 = classification_report(y_test,model2_pred)
print("Decision Tree Classification_report:\n",class_report2)

Decision Tree Classification_report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56656
           1       0.66      0.51      0.57        90

    accuracy                           1.00     56746
   macro avg       0.83      0.76      0.79     56746
weighted avg       1.00      1.00      1.00     56746